// Markazlashgan ikona modulari — har bir ikona to'g'ridan-to'g'ri o'z faylidan import qilinadi.
// Sabab: lucide-react barrel'i `export { index as icons }` orqali BUTUN kutubxonani ushlab turadi
// (tree-shaking buziladi, ~618kB). Deep import bilan faqat kerakli ikonalar bundle'ga tushadi.
// Yangi ikona kerak bo'lsa shu yerga bitta qator qo'shing.

export { default as ArrowRight } from 'lucide-react/dist/esm/icons/arrow-right.mjs'
export { default as Radio } from 'lucide-react/dist/esm/icons/radio.mjs'
export { default as Circle } from 'lucide-react/dist/esm/icons/circle.mjs'
export { default as Users } from 'lucide-react/dist/esm/icons/users.mjs'
export { default as Shield } from 'lucide-react/dist/esm/icons/shield.mjs'
export { default as Award } from 'lucide-react/dist/esm/icons/award.mjs'
export { default as BarChart3 } from 'lucide-react/dist/esm/icons/bar-chart-3.mjs'
export { default as Bell } from 'lucide-react/dist/esm/icons/bell.mjs'
export { default as BookOpen } from 'lucide-react/dist/esm/icons/book-open.mjs'
export { default as Bot } from 'lucide-react/dist/esm/icons/bot.mjs'
export { default as Check } from 'lucide-react/dist/esm/icons/check.mjs'
export { default as ChevronDown } from 'lucide-react/dist/esm/icons/chevron-down.mjs'
export { default as ChevronLeft } from 'lucide-react/dist/esm/icons/chevron-left.mjs'
export { default as ChevronRight } from 'lucide-react/dist/esm/icons/chevron-right.mjs'
export { default as CircuitBoard } from 'lucide-react/dist/esm/icons/circuit-board.mjs'
export { default as Clock } from 'lucide-react/dist/esm/icons/clock.mjs'
export { default as Code } from 'lucide-react/dist/esm/icons/code.mjs'
export { default as Cog } from 'lucide-react/dist/esm/icons/cog.mjs'
export { default as Cpu } from 'lucide-react/dist/esm/icons/cpu.mjs'
export { default as CreditCard } from 'lucide-react/dist/esm/icons/credit-card.mjs'
export { default as Crown } from 'lucide-react/dist/esm/icons/crown.mjs'
export { default as Eye } from 'lucide-react/dist/esm/icons/eye.mjs'
export { default as EyeOff } from 'lucide-react/dist/esm/icons/eye-off.mjs'
export { default as Home } from 'lucide-react/dist/esm/icons/home.mjs'
export { default as LayoutDashboard } from 'lucide-react/dist/esm/icons/layout-dashboard.mjs'
export { default as LogOut } from 'lucide-react/dist/esm/icons/log-out.mjs'
export { default as Mail } from 'lucide-react/dist/esm/icons/mail.mjs'
export { default as MapPin } from 'lucide-react/dist/esm/icons/map-pin.mjs'
export { default as Medal } from 'lucide-react/dist/esm/icons/medal.mjs'
export { default as Menu } from 'lucide-react/dist/esm/icons/menu.mjs'
export { default as Moon } from 'lucide-react/dist/esm/icons/moon.mjs'
export { default as Phone } from 'lucide-react/dist/esm/icons/phone.mjs'
export { default as Play } from 'lucide-react/dist/esm/icons/play.mjs'
export { default as Quote } from 'lucide-react/dist/esm/icons/quote.mjs'
export { default as Search } from 'lucide-react/dist/esm/icons/search.mjs'
export { default as Send } from 'lucide-react/dist/esm/icons/send.mjs'
export { default as Settings } from 'lucide-react/dist/esm/icons/settings.mjs'
export { default as Share2 } from 'lucide-react/dist/esm/icons/share-2.mjs'
export { default as Sparkles } from 'lucide-react/dist/esm/icons/sparkles.mjs'
export { default as Star } from 'lucide-react/dist/esm/icons/star.mjs'
export { default as Sun } from 'lucide-react/dist/esm/icons/sun.mjs'
export { default as TrendingUp } from 'lucide-react/dist/esm/icons/trending-up.mjs'
export { default as Trophy } from 'lucide-react/dist/esm/icons/trophy.mjs'
export { default as User } from 'lucide-react/dist/esm/icons/user.mjs'
export { default as Wrench } from 'lucide-react/dist/esm/icons/wrench.mjs'
export { default as X } from 'lucide-react/dist/esm/icons/x.mjs'
export { default as Zap } from 'lucide-react/dist/esm/icons/zap.mjs'
